### ISSUE TITLE
Standardized Financials

### ISSUE THREAD

**Issue by firmai** [TiesdeKok/fast_xbrl_parser#1]
Hi @TiesdeKok it is great to see you are still building awesome projects! Would you perhaps know the best way to go about creating standardized financials using SEC data. I think I could probably use your parser, but then I assume I need some mapping file to help me organize and standardize accross companies to get it into an ML-ready format. Would love to hear your recommendations. 

Cheers,
Derek

**Comment by TiesdeKok** [comment]
Hi Derek,

Appreciate the kind words!

Deriving standardized financial data based on 10-K/10-Q reports is indeed a non-trivial task. Most academics rely on data intermediaries (e.g., Compustat) when working with financial data, at least in my field. Compared to working with the raw XBRL data, one of the primary benefits of these aggregators is standardization across companies. The downside is $$$ and sometimes a lack of depth (i.e., certain financials might not be included in, e.g., Compustat).

I don't believe an open-source mapping file is available to standardize the XBRL data across firms/time. Although several paid solutions use proprietary mappings to deal with this (e.g., Calcbench & Idaciti). 

Ties

**Comment by firmai** [comment]
Thanks for the thorough answer Ties. Let me know if this is ever something you will be working on, I would love to help.
